# Exercise data extracted from my-fit-week
initialExercises = [
    # Common Compound Exercises
    {
        "id": "bench-press",
        "name": "Bench Press",
        "muscleGroup": "Chest",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Mid Chest", "activationLevel": "maximal"},
            {"muscle": "Upper Chest", "activationLevel": "high"},
            {"muscle": "Lower Chest", "activationLevel": "high"},
            {"muscle": "Front Delts", "activationLevel": "high"},
            {"muscle": "Triceps (Lateral Head)", "activationLevel": "medium"},
            {"muscle": "Triceps (Medial Head)", "activationLevel": "medium"},
        ],
        "splitTypes": ["push", "upper", "perMuscleGroup"],
    },
    {
        "id": "squats",
        "name": "Squats",
        "muscleGroup": "Legs",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Quadriceps", "activationLevel": "maximal"},
            {"muscle": "Glutes (Maximus)", "activationLevel": "high"},
            {"muscle": "Hamstrings", "activationLevel": "medium"},
            {"muscle": "Erector Spinae", "activationLevel": "medium"},
            {"muscle": "Calves", "activationLevel": "low"},
        ],
        "splitTypes": ["legs", "lower", "perMuscleGroup"],
    },
    {
        "id": "barbell-rows",
        "name": "Barbell Rows",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Lats", "activationLevel": "maximal"},
            {"muscle": "Mid Traps", "activationLevel": "maximal"},
            {"muscle": "Rhomboids", "activationLevel": "maximal"},
            {"muscle": "Rear Delts", "activationLevel": "high"},
            {"muscle": "Biceps (Long Head)", "activationLevel": "medium"},
            {"muscle": "Biceps (Short Head)", "activationLevel": "medium"},
            {"muscle": "Erector Spinae", "activationLevel": "medium"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": "overhead-press",
        "name": "Overhead Press",
        "muscleGroup": "Deltoids",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Front Delts", "activationLevel": "maximal"},
            {"muscle": "Side Delts", "activationLevel": "high"},
            {"muscle": "Upper Chest", "activationLevel": "medium"},
            {"muscle": "Triceps (Lateral Head)", "activationLevel": "high"},
            {"muscle": "Triceps (Medial Head)", "activationLevel": "high"},
            {"muscle": "Serratus Anterior", "activationLevel": "medium"},
        ],
        "splitTypes": ["push", "upper", "perMuscleGroup"],
    },
    {
        "id": "deadlifts",
        "name": "Deadlifts",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Erector Spinae", "activationLevel": "maximal"},
            {"muscle": "Glutes (Maximus)", "activationLevel": "maximal"},
            {"muscle": "Hamstrings", "activationLevel": "maximal"},
            {"muscle": "Lats", "activationLevel": "high"},
            {"muscle": "Mid Traps", "activationLevel": "high"},
            {"muscle": "Quadriceps", "activationLevel": "medium"},
            {"muscle": "Forearm Flexors", "activationLevel": "high"},
        ],
        "splitTypes": ["pull", "legs", "lower", "perMuscleGroup"],
    },
    # Deltoids
    {
        "id": 1,
        "name": "Side Bent Lateral Raise",
        "muscleGroup": "Deltoids",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Side Delts", "activationLevel": "maximal"},
            {"muscle": "Rear Delts", "activationLevel": "medium"},
            {"muscle": "Front Delts", "activationLevel": "low"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 3,
        "name": "Barbell Upright Row (Slow Eccentric)",
        "muscleGroup": "Deltoids",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Front Delts", "activationLevel": "maximal"},
            {"muscle": "Upper Traps", "activationLevel": "maximal"},
            {"muscle": "Side Delts", "activationLevel": "high"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 4,
        "name": "Super ROM Raises",
        "muscleGroup": "Deltoids",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Side Delts", "activationLevel": "maximal"},
            {"muscle": "Rear Delts", "activationLevel": "maximal"},
            {"muscle": "Lower Traps", "activationLevel": "high"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    # Back
    {
        "id": 5,
        "name": "45° Dumbbell Row on 30° Bench",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Rear Delts", "activationLevel": "maximal"},
            {"muscle": "Mid Traps", "activationLevel": "maximal"},
            {"muscle": "Rhomboids", "activationLevel": "maximal"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 6,
        "name": "Shoulder Shrugs",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Upper Traps", "activationLevel": "maximal"},
            {"muscle": "Mid Traps", "activationLevel": "medium"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 7,
        "name": "Dumbbell Pullover",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Lats", "activationLevel": "maximal"},
            {"muscle": "Mid Chest", "activationLevel": "medium"},
            {"muscle": "Serratus Anterior", "activationLevel": "medium"},
            {"muscle": "Triceps (Long Head)", "activationLevel": "medium"},
            {"muscle": "Triceps (Lateral Head)", "activationLevel": "low"},
        ],
        "splitTypes": ["push", "pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 8,
        "name": "Barbell Bent-Over Row (45-90 degrees)",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Mid Traps", "activationLevel": "maximal"},
            {"muscle": "Lats", "activationLevel": "high"},
            {"muscle": "Rhomboids", "activationLevel": "maximal"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 9,
        "name": "Dumbbell Chest Supported Row",
        "muscleGroup": "Back",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Lats", "activationLevel": "maximal"},
            {"muscle": "Mid Traps", "activationLevel": "high"},
            {"muscle": "Rear Delts", "activationLevel": "maximal"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    # Chest Isolation
    {
        "id": 10,
        "name": "Deficit Push-Ups",
        "muscleGroup": "Chest",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Mid Chest", "activationLevel": "maximal"},
            {"muscle": "Lower Chest", "activationLevel": "high"},
            {"muscle": "Triceps (Long Head)", "activationLevel": "high"},
            {"muscle": "Triceps (Lateral Head)", "activationLevel": "medium"},
            {"muscle": "Triceps (Medial Head)", "activationLevel": "low"},
        ],
        "splitTypes": ["push", "upper"],
    },
    {
        "id": 11,
        "name": "Dumbbell Fly (Lying Down)",
        "muscleGroup": "Chest",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Mid Chest", "activationLevel": "maximal"},
            {"muscle": "Lower Chest", "activationLevel": "high"},
        ],
        "splitTypes": ["push", "upper", "perMuscleGroup"],
    },
    {
        "id": 12,
        "name": "Dips (Legs Behind)",
        "muscleGroup": "Chest",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Lower Chest", "activationLevel": "maximal"},
            {"muscle": "Upper Chest", "activationLevel": "high"},
            {"muscle": "Triceps (Long Head)", "activationLevel": "high"},
            {"muscle": "Triceps (Lateral Head)", "activationLevel": "medium"},
            {"muscle": "Triceps (Medial Head)", "activationLevel": "low"},
        ],
        "splitTypes": ["push", "upper", "perMuscleGroup"],
    },
    {
        "id": 13,
        "name": "Incline Dumbbell Press (15°/30°)",
        "muscleGroup": "Chest",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Upper Chest", "activationLevel": "maximal"},
            {"muscle": "Mid Chest", "activationLevel": "high"},
            {"muscle": "Front Delts", "activationLevel": "medium"},
        ],
        "splitTypes": ["push", "upper", "perMuscleGroup"],
    },
    # Planche (Chest)
    {
        "id": 14,
        "name": "Leaning Push-Ups",
        "muscleGroup": "Chest",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Mid Chest", "activationLevel": "maximal"},
            {"muscle": "Lower Chest", "activationLevel": "high"},
            {"muscle": "Front Delts", "activationLevel": "maximal"},
        ],
        "calisthenicsType": "Planche",
        "splitTypes": ["push", "upper", "calisthenics", "perMuscleGroup"],
    },
    {
        "id": 15,
        "name": "Leaning Parallette Push-Ups",
        "muscleGroup": "Chest",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Mid Chest", "activationLevel": "maximal"},
            {"muscle": "Lower Chest", "activationLevel": "high"},
            {"muscle": "Front Delts", "activationLevel": "maximal"},
        ],
        "calisthenicsType": "Planche",
        "splitTypes": ["push", "upper", "calisthenics", "perMuscleGroup"],
    },
    # Core
    {
        "id": 21,
        "name": "Dumbbell Side Bend",
        "muscleGroup": "Core",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Obliques", "activationLevel": "maximal"},
            {"muscle": "Upper Abs", "activationLevel": "medium"},
            {"muscle": "Lower Abs", "activationLevel": "medium"},
        ],
        "splitTypes": ["abs", "upper", "perMuscleGroup"],
    },
    {
        "id": 22,
        "name": "Dragon Fly",
        "muscleGroup": "Core",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Upper Abs", "activationLevel": "maximal"},
            {"muscle": "Lower Abs", "activationLevel": "maximal"},
        ],
        "splitTypes": ["abs", "upper", "perMuscleGroup"],
    },
    {
        "id": 23,
        "name": "V-Ups",
        "muscleGroup": "Core",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Upper Abs", "activationLevel": "maximal"},
            {"muscle": "Lower Abs", "activationLevel": "maximal"},
        ],
        "splitTypes": ["abs", "upper", "perMuscleGroup"],
    },
    {
        "id": 24,
        "name": "Cable Crunch",
        "muscleGroup": "Core",
        "weightType": "machine",
        "targetMuscles": [
            {"muscle": "Upper Abs", "activationLevel": "maximal"},
            {"muscle": "Lower Abs", "activationLevel": "high"},
            {"muscle": "Obliques", "activationLevel": "medium"}
        ],
        "splitTypes": ["abs", "upper", "perMuscleGroup"],
    },
    {
        "id": 25,
        "name": "Standard Crunch",
        "muscleGroup": "Core",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Upper Abs", "activationLevel": "medium"},
        ],
        "splitTypes": ["abs", "upper", "perMuscleGroup"],
    },
    {
        "id": 26,
        "name": "Bicycle Crunch",
        "muscleGroup": "Core",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Upper Abs", "activationLevel": "maximal"},
            {"muscle": "Lower Abs", "activationLevel": "maximal"},
            {"muscle": "Obliques", "activationLevel": "maximal"},
        ],
        "splitTypes": ["abs", "upper", "perMuscleGroup"],
    },
    # Legs
    {
        "id": 29,
        "name": "Deadlift with Dumbbells",
        "muscleGroup": "Legs",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Glutes", "activationLevel": "maximal"},
            {"muscle": "Hamstrings", "activationLevel": "maximal"},
            {"muscle": "Erector Spinae", "activationLevel": "high"},
        ],
        "splitTypes": ["legs", "lower"],
    },
    {
        "id": 30,
        "name": "Dumbbell Stiff-Legged Deadlift",
        "muscleGroup": "Legs",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Hamstrings", "activationLevel": "maximal"},
            {"muscle": "Glutes", "activationLevel": "maximal"},
            {"muscle": "Erector Spinae", "activationLevel": "maximal"},
        ],
        "splitTypes": ["legs", "lower", "perMuscleGroup"],
    },
    {
        "id": 31,
        "name": "Dumbbell Front Squat",
        "muscleGroup": "Legs",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Quadriceps", "activationLevel": "maximal"},
            {"muscle": "Glutes", "activationLevel": "medium"},
        ],
        "splitTypes": ["legs", "lower", "perMuscleGroup"],
    },
    {
        "id": 32,
        "name": "Dumbbell Split Squat (Lunge)",
        "muscleGroup": "Legs",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Quadriceps", "activationLevel": "maximal"},
            {"muscle": "Glutes", "activationLevel": "maximal"},
            {"muscle": "Hamstrings", "activationLevel": "medium"},
        ],
        "splitTypes": ["legs", "lower", "perMuscleGroup"],
    },
    {
        "id": 33,
        "name": "Pistol Squats",
        "muscleGroup": "Legs",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Quadriceps", "activationLevel": "maximal"},
            {"muscle": "Glutes", "activationLevel": "maximal"},
        ],
        "splitTypes": ["legs", "lower", "calisthenics", "perMuscleGroup"],
    },
    {
        "id": 34,
        "name": "Standing Calf Raises",
        "muscleGroup": "Legs",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Calves", "activationLevel": "maximal"},
        ],
        "splitTypes": ["legs", "lower", "perMuscleGroup"],
    },
    # Pull-Ups
    {
        "id": 35,
        "name": "Wide Pull-Ups",
        "muscleGroup": "Back",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Lats", "activationLevel": "maximal"},
            {"muscle": "Upper Traps", "activationLevel": "high"},
            {"muscle": "Biceps (Long Head)", "activationLevel": "medium"},
            {"muscle": "Biceps (Short Head)", "activationLevel": "medium"},
            {"muscle": "Brachialis", "activationLevel": "medium"},
        ],
        "calisthenicsType": "Pull-Ups",
        "splitTypes": ["pull", "upper", "calisthenics", "perMuscleGroup"],
    },
    {
        "id": 36,
        "name": "Standard Pull-Ups",
        "muscleGroup": "Back",
        "weightType": "body",
        "targetMuscles": [
            {"muscle": "Lats", "activationLevel": "maximal"},
            {"muscle": "Biceps (Long Head)", "activationLevel": "high"},
            {"muscle": "Biceps (Short Head)", "activationLevel": "high"},
            {"muscle": "Brachialis", "activationLevel": "medium"},
            {"muscle": "Rhomboids", "activationLevel": "medium"},
        ],
        "calisthenicsType": "Pull-Ups",
        "splitTypes": ["pull", "upper", "calisthenics", "perMuscleGroup"],
    },
    # Biceps
    {
        "id": 48,
        "name": "Seated Concentration Curls",
        "muscleGroup": "Biceps",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Biceps (Short Head)", "activationLevel": "maximal"},
            {"muscle": "Biceps (Long Head)", "activationLevel": "high"},
            {"muscle": "Brachialis", "activationLevel": "high"},
            {"muscle": "Front Delts", "activationLevel": "low"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    {
        "id": 49,
        "name": "Spider Curls",
        "muscleGroup": "Biceps",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Brachialis", "activationLevel": "maximal"},
            {"muscle": "Biceps (Long Head)", "activationLevel": "medium"},
            {"muscle": "Biceps (Short Head)", "activationLevel": "medium"},
            {"muscle": "Rear Delts", "activationLevel": "low"},
        ],
        "splitTypes": ["pull", "upper", "perMuscleGroup"],
    },
    # Triceps
    {
        "id": 69,
        "name": "Skull Crusher",
        "muscleGroup": "Triceps",
        "weightType": "free",
        "targetMuscles": [
            {"muscle": "Triceps (Long Head)", "activationLevel": "maximal"},
            {"muscle": "Triceps (Lateral Head)", "activationLevel": "high"},
            {"muscle": "Triceps (Medial Head)", "activationLevel": "medium"},
            {"muscle": "Front Delts", "activationLevel": "low"},
        ],
        "splitTypes": ["push", "upper", "perMuscleGroup"],
    },
]